[package]
name = "coronacard"
version = "0.1.0"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
greenpass = "0.2.0"
image = { version = "0.23.14", default-features = false, features = ["png"] }
qrcode = { version = "0.12.0", default-features = false, features = ["svg"] }
rqrr = {version = "0.4.0", default-features = false }
xmltree = "0.10.3"
