[package]
name = "coronacard"
version = "0.1.0"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
license = "MIT"
edition = "2021"

[features]
default = ["cli"]
cli = ["clap"]

[dependencies]
greenpass = { version = "0.2.0", default-features = false }
xmltree = "0.10.3"
clap = { version = "3.0.13", default-features = false, features = ["color", "derive"], optional = true }
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
qrcode = { version = "0.12.0", default-features = false, features = ["svg"] }
rqrr = { version = "0.4.0", default-features = false }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"

[workspace]
members = ["wasm"]

[[bin]]
name = "coronacard"
required-features = ["cli"]