[package]
name = "coronacard"
version = "0.1.0"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
greenpass = "0.2.0"
image = "0.23.14"
qrcode = "0.12.0"
rqrr = "0.4.0"

